Repository SOCI/soci, pull requests merged in 2018-05, with the labels that each got.

#615 Fixing uninitialized gotData_ in soci::statement #609
  include/soci/statement.h
Labels: Category/Annoyance, Core

#618 Issue #617: CMAKE_BUILD_TYPE=RelWithDebInfo build fails with "may be …
  include/soci/values.h
Labels: Core

#638 Update FindODBC with module proposed to CMake
  cmake/modules/FindODBC.cmake
Labels: CMake, ODBC
